[project]
authors = "Justin Neil"
name = "web-scraper"
version = "0.1.0"
description = "Web scraper utility"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
    "mysql-connector-python==9.4.0",
    "lxml",
    "jproperties",
    "jsonpath-ng"
]
